#!/bin/bash

# DESCRIPTION: Send gpg mail with swaks
# USAGE: gpg-swaks "<message>" [ [<recipient mail>] [subject] ] 
# REMARK: postfix, swaks should be installed

# variables to be set
SUBJECT="$(date +"%d-%m-%Y,%H:%M:%S")"
MAIL_SENDER=naim.bougacha@epfl.ch
MAIL_RECIPIENT=malik.bougacha@epfl.ch

service postfix start
swaks --tls --header "Subject: $SUBJECT" --body <(echo "$1" | gpg -a -e -r $MAIL_RECIPIENT)  -t $MAIL_RECIPIENT -f $MAIL_SENDER
