#!/bin/bash

# USAGE
#   gpg-export-secret-keys-pdf <key ID> [<PDF output>]
#
# DESCRIPTION
#   Export the given secret key in base16 in a pdf file 
#
# REMARK
#   Requires `gnupg`,`enscript`,`paperkey` and `ps2pdf`. 
#
# VARIABLE TO BE SET
    DEFAULT_PDF_FILENAME="/tmp/privkey_${1}.pdf"
    TEXT_SIZE=7

paperkey --secret-key <(gpg --export-secret-key $1)| pr -tw132 -2  |  enscript -f Courrier$TEXT_SIZE -B -o - | ps2pdf - ${2:-$DEFAULT_PDF_FILENAME}
echo "Key exported in pdf at ${2:-$DEFAULT_PDF_FILENAME}"

