#!/bin/bash

# USAGE: rpi-kali-curl [<sdcard device>] 
# DESCRIPTION: Burn Kali on a SDCard for a Rapsberry Pi 3 
# VARIABLE TO BE SET
	MOUNTPOINT=/mnt/mmcblk0p2
	SDCARD_PATH=/dev/mmcblk0p2
 
curl -s -L "https://images.offensive-security.com/arm-images/kali-2.1.2-rpi2.img.xz" | xzcat | dd of=${@:-/dev/mmcblk0} status=progress bs=512k 

# MOUNT CARD
umount $SDCARD_PATH
mkdir $MOUNTPOINT
mount $SDCARD_PATH $MOUNTPOINT

# ADD NETWORK INTERFACE
echo "auto wlan0
allow-hotplug wlan0
iface wlan0 inet dhcp
wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
iface default inet dhcp" >> $MOUNTPOINT/etc/network/interfaces

echo 'network={
               ssid="kiwi24"
               scan_ssid=1
               key_mgmt=WPA-PSK
               psk="avpuf237"
          }' > /etc/wpa_supplicant/wpa_supplicant.conf

echo 'zsh' > /etc/root/.bashrc
cp /root/.zshrc $MOUNTPOINT/root/
echo '#!/bin/bash

apt-get install
