#!/bin/bash

# DESCRIPTION: Send mail with swaks with GPG encrypted message and attachement
# USAGE: swaks-gpg-attach <file> <message>
# REMARK: postfix, swaks should be installed

# variables to be set
SUBJECT="$(date +"%d-%m-%Y,%H:%M:%S")"
SENDER=naim@unige.ch

service postfix start
swaks -tls --header "Subject: $SUBJECT" --body <(echo "${@:2}" | gpg -a -e -r $MAIL_RECIPIENT)  -t -f $SENDER --attach <(gpg -e -r $MAIL_RECIPIENT $1  )
