#!/usr/bin/env python

# DESCRIPTION:
#   list tor nodes
# REMARK
#   requires 

from stem.control import Controller

with Controller.from_port(port = 9051) as controller:
    controller.authenticate()

    for desc in controller.get_server_descriptors():
        if desc.exit_policy.is_exiting_allowed():
            print desc.address
